# .gitignore
# ======
__pycache__

infrastructure
shared

# in addition to .gitignore
# ======
.dockerignore
.DS_Store
.elasticbeanstalk
.git
.gitignore
.prettierrc.json
.pytest_cache
.vscode
Dockerfile
etl
exploration
Makefile
